<?php

namespace ContainerDIUZTiW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ETu2zgNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eTu2zgN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\PizzaController::index' => ['privates', '.service_locator.65ghuP9.App\\Controller\\PizzaController::index()', 'getPizzaControllerindexService', true],
            'App\\Controller\\PizzaController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PizzaController::new()', 'getPizzaControllernewService', true],
            'App\\Controller\\PizzaController::show' => ['privates', '.service_locator.6Kd8BR3.App\\Controller\\PizzaController::show()', 'getPizzaControllershowService', true],
            'App\\Controller\\PizzaController::edit' => ['privates', '.service_locator.IJmTjep.App\\Controller\\PizzaController::edit()', 'getPizzaControllereditService', true],
            'App\\Controller\\PizzaController::delete' => ['privates', '.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()', 'getPizzaControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\PizzaController:index' => ['privates', '.service_locator.65ghuP9.App\\Controller\\PizzaController::index()', 'getPizzaControllerindexService', true],
            'App\\Controller\\PizzaController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PizzaController::new()', 'getPizzaControllernewService', true],
            'App\\Controller\\PizzaController:show' => ['privates', '.service_locator.6Kd8BR3.App\\Controller\\PizzaController::show()', 'getPizzaControllershowService', true],
            'App\\Controller\\PizzaController:edit' => ['privates', '.service_locator.IJmTjep.App\\Controller\\PizzaController::edit()', 'getPizzaControllereditService', true],
            'App\\Controller\\PizzaController:delete' => ['privates', '.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()', 'getPizzaControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\PizzaController::index' => '?',
            'App\\Controller\\PizzaController::new' => '?',
            'App\\Controller\\PizzaController::show' => '?',
            'App\\Controller\\PizzaController::edit' => '?',
            'App\\Controller\\PizzaController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\PizzaController:index' => '?',
            'App\\Controller\\PizzaController:new' => '?',
            'App\\Controller\\PizzaController:show' => '?',
            'App\\Controller\\PizzaController:edit' => '?',
            'App\\Controller\\PizzaController:delete' => '?',
        ]);

        if (isset($container->privates['.service_locator.eTu2zgN'])) {
            return $container->privates['.service_locator.eTu2zgN'];
        }

        return $container->privates['.service_locator.eTu2zgN'] = $instance;
    }
}
