<?php

namespace ContainerDIUZTiW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IJmTjep.App\Controller\PizzaController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.IJmTjep'] ?? $container->load('get_ServiceLocator_IJmTjepService'));

        if (isset($container->privates['.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()'])) {
            return $container->privates['.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\PizzaController::delete()', $container);

        if (isset($container->privates['.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()'])) {
            return $container->privates['.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()'];
        }

        return $container->privates['.service_locator.IJmTjep.App\\Controller\\PizzaController::delete()'] = $instance;
    }
}
