<?php

namespace ContainerDIUZTiW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.65ghuP9.App\Controller\PizzaController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.65ghuP9.App\\Controller\\PizzaController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pizzaRepository' => ['privates', 'App\\Repository\\PizzaRepository', 'getPizzaRepositoryService', true],
        ], [
            'pizzaRepository' => 'App\\Repository\\PizzaRepository',
        ]))->withContext('App\\Controller\\PizzaController::index()', $container);
    }
}
