<?php

namespace ContainerDIUZTiW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizza2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IJmTjep.App\Entity\Pizza' shared service.
     *
     * @return \App\Entity\Pizza
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IJmTjep": it needs an instance of "App\\Entity\\Pizza" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
