<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDIUZTiW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDIUZTiW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDIUZTiW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDIUZTiW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDIUZTiW\App_KernelDevDebugContainer([
    'container.build_hash' => 'DIUZTiW',
    'container.build_id' => '9ea327bd',
    'container.build_time' => 1780514999,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDIUZTiW');
