<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony.Component.Form.Form' => 0,
'IteratorAggregate' => 1,
'Symfony.Component.Form.FormInterface' => 2,
'Symfony.Component.Form.ClearableErrorsInterface' => 3,
'Traversable' => 4,
'Countable' => 5,
'ArrayAccess' => 6,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => ['Symfony\\Component\\Validator\\Mapping\\ClassMetadata', 'Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form'],
    'objectMeta' => [0, 1],
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'traversalStrategy' => [2],
            'name' => ['Symfony\\Component\\Form\\Form'],
            'defaultGroup' => ['Form'],
        ],
        'Symfony\\Component\\Validator\\Mapping\\GenericMetadata' => [
            'constraints' => [
                [1],
            ],
            'constraintsByGroup' => [
                [
                    'Default' => [1],
                    'Form' => [1],
                ],
            ],
        ],
        'stdClass' => [
            'payload' => [1 => null],
            'groups' => [
                1 => ['Default', 'Form'],
            ],
        ],
    ],
    'resolve' => [
        'Symfony\\Component\\Validator\\Mapping\\GenericMetadata' => [
            'constraints' => [
                [true],
            ],
            'constraintsByGroup' => [
                [
                    'Default' => [true],
                    'Form' => [true],
                ],
            ],
        ],
    ],
]); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => 'Symfony\\Component\\Validator\\Mapping\\ClassMetadata',
    'objectMeta' => 1,
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'name' => ['IteratorAggregate'],
            'defaultGroup' => ['IteratorAggregate'],
        ],
    ],
]); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => 'Symfony\\Component\\Validator\\Mapping\\ClassMetadata',
    'objectMeta' => 1,
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'name' => ['Symfony\\Component\\Form\\FormInterface'],
            'defaultGroup' => ['FormInterface'],
        ],
    ],
]); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => 'Symfony\\Component\\Validator\\Mapping\\ClassMetadata',
    'objectMeta' => 1,
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'name' => ['Symfony\\Component\\Form\\ClearableErrorsInterface'],
            'defaultGroup' => ['ClearableErrorsInterface'],
        ],
    ],
]); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => 'Symfony\\Component\\Validator\\Mapping\\ClassMetadata',
    'objectMeta' => 1,
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'name' => ['Traversable'],
            'defaultGroup' => ['Traversable'],
        ],
    ],
]); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => 'Symfony\\Component\\Validator\\Mapping\\ClassMetadata',
    'objectMeta' => 1,
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'name' => ['Countable'],
            'defaultGroup' => ['Countable'],
        ],
    ],
]); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \deepclone_from_array([
    'classes' => 'Symfony\\Component\\Validator\\Mapping\\ClassMetadata',
    'objectMeta' => 1,
    'prepared' => 0,
    'properties' => [
        'Symfony\\Component\\Validator\\Mapping\\ClassMetadata' => [
            'name' => ['ArrayAccess'],
            'defaultGroup' => ['ArrayAccess'],
        ],
    ],
]); } },

]];
