<?php

namespace ContainerX7mWNDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IJmTjepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IJmTjep' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pizza' => ['privates', '.errored..service_locator.IJmTjep.App\\Entity\\Pizza', NULL, 'Cannot autowire service ".service_locator.IJmTjep": it needs an instance of "App\\Entity\\Pizza" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'pizza' => 'App\\Entity\\Pizza',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.IJmTjep'])) {
            return $container->privates['.service_locator.IJmTjep'];
        }

        return $container->privates['.service_locator.IJmTjep'] = $instance;
    }
}
