<?php

namespace ContainerX7mWNDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Kd8BR3.App\Controller\PizzaController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Kd8BR3.App\\Controller\\PizzaController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pizza' => ['privates', '.errored..service_locator.6Kd8BR3.App\\Entity\\Pizza', NULL, 'Cannot autowire service ".service_locator.6Kd8BR3": it needs an instance of "App\\Entity\\Pizza" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'pizza' => 'App\\Entity\\Pizza',
        ]))->withContext('App\\Controller\\PizzaController::show()', $container);
    }
}
