<?php

namespace ContainerX7mWNDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PizzaType' shared autowired service.
     *
     * @return \App\Form\PizzaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PizzaType.php';

        return $container->privates['App\\Form\\PizzaType'] = new \App\Form\PizzaType();
    }
}
