<?php

namespace ContainerX7mWNDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6Kd8BR3.App\Entity\Pizza' shared service.
     *
     * @return \App\Entity\Pizza
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6Kd8BR3": it needs an instance of "App\\Entity\\Pizza" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
